Update readme with everything that is installed
privacycloud/.dotfiles pull request #2
Opened 2020-02-20 13:05 UTC by carmee-en

Related to #1 

This Pull Request adds more info about which apps are being installed using Homebrew. Also, it adds info on the dotfiles it installs exactly.

2020-02-21 17:34 UTC, SantiMA10 requested changes
One comment and ready 🚀

2020-02-21 17:34 UTC, SantiMA10 commented on README.md
> +   - [zsh]() and [oh my zsh](https://github.com/ohmyzsh/ohmyzsh)
We miss the zsh link, isn't it?

2020-02-25 09:03 UTC, carmee-en commented on README.md
> +   - [zsh]() and [oh my zsh](https://github.com/ohmyzsh/ohmyzsh)
Done! I also added a link for `yarn`

2020-02-25 09:25 UTC, dcarral approved these changes
Awesome @carmee-en, keep up the good work! :)

2020-02-25 09:26 UTC, merged

2020-02-25 09:27 UTC, dcarral commented
By the way @carmee-en: useful tip & trick to automatically close issues from PRs @ GitHub: https://stackoverflow.com/questions/12235620/automatically-closing-issue-from-pull-request-in-github